plugins {
  application
}

repositories {
  mavenCentral()
}

dependencies {
  implementation(libs.jaylib)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(26)
  }
}

application {
  // Define the main class for the application.
  mainClass = "Main"
}

tasks.register<Delete>("cleanJdtls") {
  group = "cleanup"
  description = "Delete things generated by the jdtls."

  delete(
    ".settings",
    "bin",
    ".classpath",
    ".project",
    rootProject.file(".project"),
    rootProject.file(".settings")
  )

  doLast {
    println("Cleaning done.")
  }
}

tasks.named("clean") {
  dependsOn("cleanJdtls")
}

tasks.named("build") {
  dependsOn("cleanJdtls")
}
